# Generated by Django 4.2.5 on 2025-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='タイトル')),
            ],
            options={
                'db_table': 'checkout',
            },
        ),
    ]
