# Generated by Django 4.2.5 on 2025-07-20 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address1',
            field=models.CharField(default='', max_length=255, verbose_name='住所1 (番地・町)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所2 (建物名・部屋番号)'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_cvv',
            field=models.CharField(default='', max_length=4, verbose_name='CVV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_expiration',
            field=models.CharField(default='', max_length=20, verbose_name='有効期限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_name',
            field=models.CharField(default='', max_length=255, verbose_name='カード名義'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_number',
            field=models.CharField(default='', max_length=20, verbose_name='カード番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(choices=[('', '選択してください'), ('JP', '日本')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注文日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='firstname',
            field=models.CharField(default='', max_length=100, verbose_name='名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='lastname',
            field=models.CharField(default='', max_length=100, verbose_name='姓'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='state',
            field=models.CharField(choices=[('', '選択してください'), ('JP', '日本')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='ユーザー名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='zip',
            field=models.CharField(default='', max_length=20, verbose_name='郵便番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='メールアドレス'),
        ),
        migrations.CreateModel(
            name='CheckoutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル')),
                ('price', models.IntegerField(blank=True, verbose_name='価格')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='商品画像')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='説明')),
                ('quantity', models.IntegerField(blank=True, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout', verbose_name='購入明細')),
            ],
            options={
                'db_table': 'checkout_items',
            },
        ),
    ]
