# Generated by Django 4.2.5 on 2025-07-20 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('checkout', '0002_checkout_address1_checkout_address2_and_more'), ('checkout', '0003_alter_checkout_state'), ('checkout', '0004_alter_checkout_country_alter_checkout_state')]

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address1',
            field=models.CharField(default='', max_length=255, verbose_name='住所1 (番地・町)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所2 (建物名・部屋番号)'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_cvv',
            field=models.CharField(default='', max_length=4, verbose_name='CVV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_expiration',
            field=models.CharField(default='', max_length=20, verbose_name='有効期限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_name',
            field=models.CharField(default='', max_length=255, verbose_name='カード名義'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_number',
            field=models.CharField(default='', max_length=20, verbose_name='カード番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(choices=[('', '選択してください'), ('JP', '日本')], max_length=100, verbose_name='国'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注文日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='firstname',
            field=models.CharField(default='', max_length=100, verbose_name='名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='lastname',
            field=models.CharField(default='', max_length=100, verbose_name='姓'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='state',
            field=models.CharField(choices=[('', '選択してください'), ('JP-01', '北海道'), ('JP-02', '青森県'), ('JP-03', '岩手県'), ('JP-04', '宮城県'), ('JP-05', '秋田県'), ('JP-06', '山形県'), ('JP-07', '福島県'), ('JP-08', '茨城県'), ('JP-09', '栃木県'), ('JP-10', '群馬県'), ('JP-11', '埼玉県'), ('JP-12', '千葉県'), ('JP-13', '東京都'), ('JP-14', '神奈川県'), ('JP-15', '新潟県'), ('JP-16', '富山県'), ('JP-17', '石川県'), ('JP-18', '福井県'), ('JP-19', '山梨県'), ('JP-20', '長野県'), ('JP-21', '岐阜県'), ('JP-22', '静岡県'), ('JP-23', '愛知県'), ('JP-24', '三重県'), ('JP-25', '滋賀県'), ('JP-26', '京都府'), ('JP-27', '大阪府'), ('JP-28', '兵庫県'), ('JP-29', '奈良県'), ('JP-30', '和歌山県'), ('JP-31', '鳥取県'), ('JP-32', '島根県'), ('JP-33', '岡山県'), ('JP-34', '広島県'), ('JP-35', '山口県'), ('JP-36', '徳島県'), ('JP-37', '香川県'), ('JP-38', '愛媛県'), ('JP-39', '高知県'), ('JP-40', '福岡県'), ('JP-41', '佐賀県'), ('JP-42', '長崎県'), ('JP-43', '熊本県'), ('JP-44', '大分県'), ('JP-45', '宮崎県'), ('JP-46', '鹿児島県'), ('JP-47', '沖縄県')], max_length=100, verbose_name='県'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='ユーザー名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='zip',
            field=models.CharField(default='', max_length=20, verbose_name='郵便番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='メールアドレス'),
        ),
        migrations.CreateModel(
            name='CheckoutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル')),
                ('price', models.IntegerField(blank=True, verbose_name='価格')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='商品画像')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='説明')),
                ('quantity', models.IntegerField(blank=True, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout', verbose_name='購入明細')),
            ],
            options={
                'db_table': 'checkout_items',
            },
        ),
    ]
