# Generated by Django 4.2.5 on 2025-07-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_address1_checkout_address2_and_more_squashed_0004_alter_checkout_country_alter_checkout_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitems',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='checkoutitems',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='checkoutitems',
            name='price',
            field=models.IntegerField(verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='checkoutitems',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='checkoutitems',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
    ]
