# Generated by Django 4.2.5 on 2025-07-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_checkoutitems_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutitems',
            old_name='order',
            new_name='checkout',
        ),
    ]
