# Generated by Django 4.2.5 on 2025-07-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_order_checkoutitems_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitems',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckoutItems', to='checkout.checkout', verbose_name='購入明細'),
        ),
    ]
