# Generated by Django 4.2.5 on 2025-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_checkoutitems_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='プロモーションコード'),
        ),
    ]
