# Generated by Django 4.2.5 on 2025-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_checkout_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='割引額'),
        ),
    ]
