# Generated by Django 4.2.5 on 2025-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル')),
                ('price', models.IntegerField(blank=True, verbose_name='価格')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='商品画像')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
