# Generated by Django 4.2.5 on 2025-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.ImageField(blank=True, max_length=1000, upload_to='', verbose_name='商品説明'),
        ),
    ]
