# Generated by Django 4.2.5 on 2025-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='説明'),
        ),
    ]
