# Generated by Django 4.2.5 on 2025-07-16 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_items_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, verbose_name='数量')),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.carts', verbose_name='カート')),
                ('items', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='商品')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
    ]
