# Generated by Django 4.2.5 on 2025-07-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_carts_cartsitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsitems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='商品'),
        ),
    ]
