# Generated by Django 4.2.5 on 2025-07-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_cartsitems_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartsItems',
            new_name='CartItems',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='carts',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='items',
            new_name='item',
        ),
    ]
