# Generated by Django 4.2.5 on 2025-07-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_cartsitems_cartitems_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitems',
            table='cart_items',
        ),
        migrations.AlterModelTable(
            name='carts',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
    ]
