# Generated by Django 4.2.5 on 2025-07-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=7, verbose_name='プロモーションコード')),
                ('discount_price', models.IntegerField(verbose_name='割引額')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済みフラグ')),
            ],
            options={
                'db_table': 'promotioncode',
            },
        ),
    ]
