# Generated by Django 4.2.5 on 2025-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotioncode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncode',
            name='promotion_code',
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='code',
            field=models.CharField(default='', max_length=7, unique=True, verbose_name='プロモーションコード'),
            preserve_default=False,
        ),
    ]
